version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  nextjs:
    container_name: nextjs_prod_container
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
